//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmintIo.Portals.DataAdapter.Picturepark.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetamodelMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetamodelMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmintIo.Portals.DataAdapter.Picturepark.Resources.MetamodelMessages", typeof(MetamodelMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string da_assets_advanced {
            get {
                return ResourceManager.GetString("da_assets_advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string da_assets_application {
            get {
                return ResourceManager.GetString("da_assets_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string da_assets_archive {
            get {
                return ResourceManager.GetString("da_assets_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string da_assets_audio {
            get {
                return ResourceManager.GetString("da_assets_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string da_assets_bitmap {
            get {
                return ResourceManager.GetString("da_assets_bitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD.
        /// </summary>
        public static string da_assets_cad {
            get {
                return ResourceManager.GetString("da_assets_cad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string da_assets_database {
            get {
                return ResourceManager.GetString("da_assets_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop publishing document.
        /// </summary>
        public static string da_assets_desktop_publishing_document {
            get {
                return ResourceManager.GetString("da_assets_desktop_publishing_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string da_assets_font {
            get {
                return ResourceManager.GetString("da_assets_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interchange document.
        /// </summary>
        public static string da_assets_interchange_document {
            get {
                return ResourceManager.GetString("da_assets_interchange_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D model.
        /// </summary>
        public static string da_assets_model_3d {
            get {
                return ResourceManager.GetString("da_assets_model_3d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia.
        /// </summary>
        public static string da_assets_multimedia {
            get {
                return ResourceManager.GetString("da_assets_multimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation.
        /// </summary>
        public static string da_assets_presentation {
            get {
                return ResourceManager.GetString("da_assets_presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw image.
        /// </summary>
        public static string da_assets_raw_image {
            get {
                return ResourceManager.GetString("da_assets_raw_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search type.
        /// </summary>
        public static string da_assets_search_type {
            get {
                return ResourceManager.GetString("da_assets_search_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple AND.
        /// </summary>
        public static string da_assets_simple_and {
            get {
                return ResourceManager.GetString("da_assets_simple_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple OR.
        /// </summary>
        public static string da_assets_simple_or {
            get {
                return ResourceManager.GetString("da_assets_simple_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string da_assets_source_code {
            get {
                return ResourceManager.GetString("da_assets_source_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreadsheet.
        /// </summary>
        public static string da_assets_spread_sheet {
            get {
                return ResourceManager.GetString("da_assets_spread_sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text document.
        /// </summary>
        public static string da_assets_text_document {
            get {
                return ResourceManager.GetString("da_assets_text_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string da_assets_unknown {
            get {
                return ResourceManager.GetString("da_assets_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector illustration.
        /// </summary>
        public static string da_assets_vector_graphic {
            get {
                return ResourceManager.GetString("da_assets_vector_graphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string da_assets_video {
            get {
                return ResourceManager.GetString("da_assets_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual object.
        /// </summary>
        public static string da_assets_virtual {
            get {
                return ResourceManager.GetString("da_assets_virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word processing document.
        /// </summary>
        public static string da_assets_word_processing_document {
            get {
                return ResourceManager.GetString("da_assets_word_processing_document", resourceCulture);
            }
        }
    }
}
