//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmintIo.Portals.Connector.Picturepark.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigurationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmintIo.Portals.Connector.Picturepark.Resources.ConfigurationMessages", typeof(ConfigurationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access token for your Picturepark API Client. You can set up the API client in Picturepark Content Platform by visiting Settings &gt; API Clients &gt; Create New. Use the password method. Once the API client has been created you can create the access token..
        /// </summary>
        public static string c_picturepark_access_token_description {
            get {
                return ResourceManager.GetString("c_picturepark_access_token_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your access token.
        /// </summary>
        public static string c_picturepark_access_token_display_name {
            get {
                return ResourceManager.GetString("c_picturepark_access_token_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Picturepark channel to use..
        /// </summary>
        public static string c_picturepark_channel_description {
            get {
                return ResourceManager.GetString("c_picturepark_channel_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string c_picturepark_channel_display_name {
            get {
                return ResourceManager.GetString("c_picturepark_channel_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connects Smint.io Portals to the Picturepark Content Platform..
        /// </summary>
        public static string c_picturepark_description {
            get {
                return ResourceManager.GetString("c_picturepark_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the legacy thumbnail override mode. Please only enable if instructed to do so by Smint.io support..
        /// </summary>
        public static string c_picturepark_legacy_thumbnails_enabled_description {
            get {
                return ResourceManager.GetString("c_picturepark_legacy_thumbnails_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable legacy thumbnail override mode.
        /// </summary>
        public static string c_picturepark_legacy_thumbnails_enabled_display_name {
            get {
                return ResourceManager.GetString("c_picturepark_legacy_thumbnails_enabled_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picturepark Content Platform.
        /// </summary>
        public static string c_picturepark_name {
            get {
                return ResourceManager.GetString("c_picturepark_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web address of your Picturepark Content Platform instance. Please visit Picturepark Content Platform, log in, and then copy the URL from the browser address bar. Finally, paste the copied URL here..
        /// </summary>
        public static string c_picturepark_picturepark_url_description {
            get {
                return ResourceManager.GetString("c_picturepark_picturepark_url_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Picturepark URL.
        /// </summary>
        public static string c_picturepark_picturepark_url_display_name {
            get {
                return ResourceManager.GetString("c_picturepark_picturepark_url_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.picturepark.com.
        /// </summary>
        public static string c_picturepark_setup_documentation_url {
            get {
                return ResourceManager.GetString("c_picturepark_setup_documentation_url", resourceCulture);
            }
        }
    }
}
