//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmintIo.Portals.Connector.SharePoint.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigurationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmintIo.Portals.Connector.SharePoint.Resources.ConfigurationMessages", typeof(ConfigurationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the client ID of the Azure app registration..
        /// </summary>
        public static string c_sharepoint_client_id_description {
            get {
                return ResourceManager.GetString("c_sharepoint_client_id_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure client ID.
        /// </summary>
        public static string c_sharepoint_client_id_display_name {
            get {
                return ResourceManager.GetString("c_sharepoint_client_id_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the client secret of the Azure app registration..
        /// </summary>
        public static string c_sharepoint_client_secret_description {
            get {
                return ResourceManager.GetString("c_sharepoint_client_secret_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure client secret.
        /// </summary>
        public static string c_sharepoint_client_secret_display_name {
            get {
                return ResourceManager.GetString("c_sharepoint_client_secret_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this SharePoint connector is to be used in high security environments, please activate this option. Please note that some convenience features of the connector will then be turned off, e.g. the ability to easily select the SharePoint site from a drop-down list. This feature should be used by experts only..
        /// </summary>
        public static string c_sharepoint_high_security_mode_description {
            get {
                return ResourceManager.GetString("c_sharepoint_high_security_mode_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High security mode (only for experts).
        /// </summary>
        public static string c_sharepoint_high_security_mode_display_name {
            get {
                return ResourceManager.GetString("c_sharepoint_high_security_mode_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web address of your SharePoint instance. Please visit SharePoint, log in, and then copy the URL from the browser address bar. Finally, paste the copied URL here..
        /// </summary>
        public static string c_sharepoint_sharepoint_url_description {
            get {
                return ResourceManager.GetString("c_sharepoint_sharepoint_url_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your SharePoint URL.
        /// </summary>
        public static string c_sharepoint_sharepoint_url_display_name {
            get {
                return ResourceManager.GetString("c_sharepoint_sharepoint_url_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the SharePoint drive whose documents structure should be processed by this connector..
        /// </summary>
        public static string c_sharepoint_site_drive_id_description {
            get {
                return ResourceManager.GetString("c_sharepoint_site_drive_id_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint drive.
        /// </summary>
        public static string c_sharepoint_site_drive_id_display_name {
            get {
                return ResourceManager.GetString("c_sharepoint_site_drive_id_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the SharePoint drive whose documents structure should be processed by this connector..
        /// </summary>
        public static string c_sharepoint_site_drive_id_string_description {
            get {
                return ResourceManager.GetString("c_sharepoint_site_drive_id_string_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint drive.
        /// </summary>
        public static string c_sharepoint_site_drive_id_string_display_name {
            get {
                return ResourceManager.GetString("c_sharepoint_site_drive_id_string_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the SharePoint folders whose documents structure should be processed by this connector..
        /// </summary>
        public static string c_sharepoint_site_folder_ids_description {
            get {
                return ResourceManager.GetString("c_sharepoint_site_folder_ids_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint folders to sync.
        /// </summary>
        public static string c_sharepoint_site_folder_ids_display_name {
            get {
                return ResourceManager.GetString("c_sharepoint_site_folder_ids_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the SharePoint site folders whose documents structure should be processed by this connector..
        /// </summary>
        public static string c_sharepoint_site_folder_ids_string_description {
            get {
                return ResourceManager.GetString("c_sharepoint_site_folder_ids_string_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint site folders to sync.
        /// </summary>
        public static string c_sharepoint_site_folder_ids_string_display_name {
            get {
                return ResourceManager.GetString("c_sharepoint_site_folder_ids_string_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the SharePoint site whose documents structure should be processed by this connector..
        /// </summary>
        public static string c_sharepoint_site_id_description {
            get {
                return ResourceManager.GetString("c_sharepoint_site_id_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint site.
        /// </summary>
        public static string c_sharepoint_site_id_display_name {
            get {
                return ResourceManager.GetString("c_sharepoint_site_id_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the SharePoint site ID of the SharePoint site whose documents structure should be processed by this connector..
        /// </summary>
        public static string c_sharepoint_site_id_string_description {
            get {
                return ResourceManager.GetString("c_sharepoint_site_id_string_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint site ID.
        /// </summary>
        public static string c_sharepoint_site_id_string_display_name {
            get {
                return ResourceManager.GetString("c_sharepoint_site_id_string_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the SharePoint list whose metadata definitions should be processed by this connector..
        /// </summary>
        public static string c_sharepoint_site_list_id_description {
            get {
                return ResourceManager.GetString("c_sharepoint_site_list_id_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint list.
        /// </summary>
        public static string c_sharepoint_site_list_id_display_name {
            get {
                return ResourceManager.GetString("c_sharepoint_site_list_id_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the SharePoint list whose metadata definitions should be processed by this connector..
        /// </summary>
        public static string c_sharepoint_site_list_id_string_description {
            get {
                return ResourceManager.GetString("c_sharepoint_site_list_id_string_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint list.
        /// </summary>
        public static string c_sharepoint_site_list_id_string_display_name {
            get {
                return ResourceManager.GetString("c_sharepoint_site_list_id_string_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the tenant ID of the Azure app registration..
        /// </summary>
        public static string c_sharepoint_tenant_id_description {
            get {
                return ResourceManager.GetString("c_sharepoint_tenant_id_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure tenant ID.
        /// </summary>
        public static string c_sharepoint_tenant_id_display_name {
            get {
                return ResourceManager.GetString("c_sharepoint_tenant_id_display_name", resourceCulture);
            }
        }
    }
}
