//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmintIo.Portals.Connector.SharePoint.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OneDriveConfigurationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OneDriveConfigurationMessages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmintIo.Portals.Connector.SharePoint.Resources.OneDriveConfigurationMessages", typeof(OneDriveConfigurationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the client ID of the Azure app registration. ähnelt.
        /// </summary>
        public static string c_onedrive_client_id_description {
            get {
                return ResourceManager.GetString("c_onedrive_client_id_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Azure client ID ähnelt.
        /// </summary>
        public static string c_onedrive_client_id_display_name {
            get {
                return ResourceManager.GetString("c_onedrive_client_id_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the client secret of the Azure app registration. ähnelt.
        /// </summary>
        public static string c_onedrive_client_secret_description {
            get {
                return ResourceManager.GetString("c_onedrive_client_secret_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Azure client secret ähnelt.
        /// </summary>
        public static string c_onedrive_client_secret_display_name {
            get {
                return ResourceManager.GetString("c_onedrive_client_secret_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connects Smint.io Portals to Microsoft OneDrive. ähnelt.
        /// </summary>
        public static string c_onedrive_description {
            get {
                return ResourceManager.GetString("c_onedrive_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If this OneDrive connector is to be used in high security environments, please activate this option. Please note that some convenience features of the connector will then be turned off, e.g. the ability to easily select the SharePoint site from a drop-down list. This feature should be used by experts only. ähnelt.
        /// </summary>
        public static string c_onedrive_high_security_mode_description {
            get {
                return ResourceManager.GetString("c_onedrive_high_security_mode_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die High security mode (only for experts) ähnelt.
        /// </summary>
        public static string c_onedrive_high_security_mode_display_name {
            get {
                return ResourceManager.GetString("c_onedrive_high_security_mode_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft OneDrive ähnelt.
        /// </summary>
        public static string c_onedrive_name {
            get {
                return ResourceManager.GetString("c_onedrive_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.microsoft.com/microsoft-365/onedrive ähnelt.
        /// </summary>
        public static string c_onedrive_setup_documentation_url {
            get {
                return ResourceManager.GetString("c_onedrive_setup_documentation_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This connector connects to OneDrive using your SharePoint instance. Please enter the web address of your SharePoint instance. Please visit SharePoint, log in, and then copy the URL from the browser address bar. Finally, paste the copied URL here. ähnelt.
        /// </summary>
        public static string c_onedrive_sharepoint_url_description {
            get {
                return ResourceManager.GetString("c_onedrive_sharepoint_url_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your SharePoint URL (required to connect to OneDrive) ähnelt.
        /// </summary>
        public static string c_onedrive_sharepoint_url_display_name {
            get {
                return ResourceManager.GetString("c_onedrive_sharepoint_url_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the OneDrive drive whose documents structure should be processed by this connector. ähnelt.
        /// </summary>
        public static string c_onedrive_site_drive_id_description {
            get {
                return ResourceManager.GetString("c_onedrive_site_drive_id_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OneDrive drive ähnelt.
        /// </summary>
        public static string c_onedrive_site_drive_id_display_name {
            get {
                return ResourceManager.GetString("c_onedrive_site_drive_id_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the OneDrive drive whose documents structure should be processed by this connector. ähnelt.
        /// </summary>
        public static string c_onedrive_site_drive_id_string_description {
            get {
                return ResourceManager.GetString("c_onedrive_site_drive_id_string_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OneDrive drive ähnelt.
        /// </summary>
        public static string c_onedrive_site_drive_id_string_display_name {
            get {
                return ResourceManager.GetString("c_onedrive_site_drive_id_string_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the OneDrive folders whose documents structure should be processed by this connector. ähnelt.
        /// </summary>
        public static string c_onedrive_site_folder_ids_description {
            get {
                return ResourceManager.GetString("c_onedrive_site_folder_ids_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OneDrive folders to sync ähnelt.
        /// </summary>
        public static string c_onedrive_site_folder_ids_display_name {
            get {
                return ResourceManager.GetString("c_onedrive_site_folder_ids_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the SharePoint site folders whose documents structure should be processed by this connector. ähnelt.
        /// </summary>
        public static string c_onedrive_site_folder_ids_string_description {
            get {
                return ResourceManager.GetString("c_onedrive_site_folder_ids_string_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SharePoint site folders to sync ähnelt.
        /// </summary>
        public static string c_onedrive_site_folder_ids_string_display_name {
            get {
                return ResourceManager.GetString("c_onedrive_site_folder_ids_string_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the SharePoint site whose documents structure should be processed by this connector. ähnelt.
        /// </summary>
        public static string c_onedrive_site_id_description {
            get {
                return ResourceManager.GetString("c_onedrive_site_id_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SharePoint site ähnelt.
        /// </summary>
        public static string c_onedrive_site_id_display_name {
            get {
                return ResourceManager.GetString("c_onedrive_site_id_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the SharePoint site ID of the SharePoint site whose documents structure should be processed by this connector. ähnelt.
        /// </summary>
        public static string c_onedrive_site_id_string_description {
            get {
                return ResourceManager.GetString("c_onedrive_site_id_string_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SharePoint site ID ähnelt.
        /// </summary>
        public static string c_onedrive_site_id_string_display_name {
            get {
                return ResourceManager.GetString("c_onedrive_site_id_string_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the SharePoint list whose metadata definitions should be processed by this connector. ähnelt.
        /// </summary>
        public static string c_onedrive_site_list_id_description {
            get {
                return ResourceManager.GetString("c_onedrive_site_list_id_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SharePoint list ähnelt.
        /// </summary>
        public static string c_onedrive_site_list_id_display_name {
            get {
                return ResourceManager.GetString("c_onedrive_site_list_id_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the SharePoint list whose metadata definitions should be processed by this connector. ähnelt.
        /// </summary>
        public static string c_onedrive_site_list_id_string_description {
            get {
                return ResourceManager.GetString("c_onedrive_site_list_id_string_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SharePoint list ähnelt.
        /// </summary>
        public static string c_onedrive_site_list_id_string_display_name {
            get {
                return ResourceManager.GetString("c_onedrive_site_list_id_string_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the tenant ID of the Azure app registration. ähnelt.
        /// </summary>
        public static string c_onedrive_tenant_id_description {
            get {
                return ResourceManager.GetString("c_onedrive_tenant_id_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Azure tenant ID ähnelt.
        /// </summary>
        public static string c_onedrive_tenant_id_display_name {
            get {
                return ResourceManager.GetString("c_onedrive_tenant_id_display_name", resourceCulture);
            }
        }
    }
}
