//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmintIo.Portals.DataAdapter.Picturepark.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigurationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmintIo.Portals.DataAdapter.Picturepark.Resources.ConfigurationMessages", typeof(ConfigurationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data mapping.
        /// </summary>
        public static string da_assets_data_mapping_form_group_display_name {
            get {
                return ResourceManager.GetString("da_assets_data_mapping_form_group_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default size of a search result page..
        /// </summary>
        public static string da_assets_default_page_size_description {
            get {
                return ResourceManager.GetString("da_assets_default_page_size_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result page size.
        /// </summary>
        public static string da_assets_default_page_size_display_name {
            get {
                return ResourceManager.GetString("da_assets_default_page_size_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Picturepark display pattern that should be used for the asset title when showing the asset in a gallery view..
        /// </summary>
        public static string da_assets_gallery_title_display_pattern_description {
            get {
                return ResourceManager.GetString("da_assets_gallery_title_display_pattern_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery title display pattern.
        /// </summary>
        public static string da_assets_gallery_title_display_pattern_display_name {
            get {
                return ResourceManager.GetString("da_assets_gallery_title_display_pattern_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your list definitions use a custom attribute for storing the display name, you can give the attribute identifier here. If no setting is specified here, or the attribute is not found, the default logic for resolving the display name is used..
        /// </summary>
        public static string da_assets_list_name_attribute_2_description {
            get {
                return ResourceManager.GetString("da_assets_list_name_attribute_2_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List value display name attribute (priority 2).
        /// </summary>
        public static string da_assets_list_name_attribute_2_display_name {
            get {
                return ResourceManager.GetString("da_assets_list_name_attribute_2_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your list definitions use a custom attribute for storing the display name, you can give the attribute identifier here. If no setting is specified here, or the attribute is not found, the default logic for resolving the display name is used..
        /// </summary>
        public static string da_assets_list_name_attribute_description {
            get {
                return ResourceManager.GetString("da_assets_list_name_attribute_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List value display name attribute (priority 1).
        /// </summary>
        public static string da_assets_list_name_attribute_display_name {
            get {
                return ResourceManager.GetString("da_assets_list_name_attribute_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string da_assets_picturepark_display_pattern_list_display_name {
            get {
                return ResourceManager.GetString("da_assets_picturepark_display_pattern_list_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string da_assets_picturepark_display_pattern_name_display_name {
            get {
                return ResourceManager.GetString("da_assets_picturepark_display_pattern_name_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading user defined data attributes of lists is very resource and data consuming. This is the reason why by default no user defined list data attributes for objects are read that reference multiple list values at the same time. Here you can specify the name of the objects where such list data attributes should be read anyways..
        /// </summary>
        public static string da_assets_resolve_list_data_attributes_description {
            get {
                return ResourceManager.GetString("da_assets_resolve_list_data_attributes_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve list data attributes for objects.
        /// </summary>
        public static string da_assets_resolve_list_data_attributes_display_name {
            get {
                return ResourceManager.GetString("da_assets_resolve_list_data_attributes_display_name", resourceCulture);
            }
        }
    }
}
